<a href="https://colab.research.google.com/github/Venu-max/NASSCOM-AI/blob/main/Day_2_NumPy_Exercise_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
## Task 1
import numpy as np

print("--- Intermediate NumPy Exercise ---")
print("Complete each task by writing the requested NumPy code.")
print("-----------------------------------")

# Task 1: Array Creation Shortcuts
print("\n--- Task 1: Array Creation Shortcuts ---")

# 1.1 Create a 1D array named 'arr1_1' with numbers from 0 to 99 (inclusive)
arr1_1 = np.arange(0, 100)

# 1.2 Create a 3x3 array filled with ones
arr1_2 = np.ones((3, 3))

# 1.3 Create a 2x4 array filled with the number 7
arr1_3 = np.full((2, 4), 7)

# 1.4 Create a 5x5 array with random integers between 10 and 50 (inclusive)
arr1_4 = np.random.randint(10, 51, size=(5, 5))

# Display the results
print("arr1_1 (first 10 elements):", arr1_1[:10])

print("\narr1_2:")
print(arr1_2)

print("\narr1_3:")
print(arr1_3)

print("\narr1_4 (first 2 rows):")
print(arr1_4[:2])

--- Intermediate NumPy Exercise ---
Complete each task by writing the requested NumPy code.
-----------------------------------

--- Task 1: Array Creation Shortcuts ---
arr1_1 (first 10 elements): [0 1 2 3 4 5 6 7 8 9]

arr1_2:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

arr1_3:
[[7 7 7 7]
 [7 7 7 7]]

arr1_4 (first 2 rows):
[[21 26 15 20 39]
 [25 29 25 29 12]]


In [2]:

# Task 2: Indexing and Slicing with Arrays

print("\n--- Task 2: Indexing and Slicing with Arrays ---")

import numpy as np

data = np.array([[10, 20, 30, 40],
                 [50, 60, 70, 80],
                 [90, 100, 110, 120],
                 [130, 140, 150, 160]])

# 2.1 Extract the element at row 2, column 3 (0-indexed)
val2_1 = data[2, 3]

# 2.2 Extract the first row
row2_2 = data[0, :]

# 2.3 Extract the last column
col2_3 = data[:, -1]

# 2.4 Extract rows 1 and 2, columns 0 and 1
sub_arr2_4 = data[1:3, 0:2]

# 2.5 Select all elements greater than 100
filtered_elements2_5 = data[data > 100]

# Print the results
print("2.1 Element at row 2, column 3:", val2_1)

print("\n2.2 First row:")
print(row2_2)

print("\n2.3 Last column:")
print(col2_3)

print("\n2.4 Sub-array (rows 1-2, columns 0-1):")
print(sub_arr2_4)

print("\n2.5 Elements greater than 100:")
print(filtered_elements2_5)


--- Task 2: Indexing and Slicing with Arrays ---
2.1 Element at row 2, column 3: 120

2.2 First row:
[10 20 30 40]

2.3 Last column:
[ 40  80 120 160]

2.4 Sub-array (rows 1-2, columns 0-1):
[[ 50  60]
 [ 90 100]]

2.5 Elements greater than 100:
[110 120 130 140 150 160]
