<a href="https://colab.research.google.com/github/Venu-max/NASSCOM-AI/blob/main/Day3_Pandas_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

print("--- Intermediate Pandas Exercise ---")
print("Complete each task by writing the requested Pandas code.")
print("------------------------------------")

# Task 1: Basic Pandas Functions and Converting Arrays to DataFrames
print("\n--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---")

# 1.1 Create a Pandas Series named 's1_1' from a list of numbers [10, 20, 30, 40, 50].
s1_1 = pd.Series([10, 20, 30, 40, 50])

print("Series:")
print(s1_1)

# 1.2 Create a 3x4 NumPy array named 'np_array1_2' with random integers between 1 and 100.
np_array1_2 = np.random.randint(1, 101, size=(3, 4))

print("\nNumPy Array:")
print(np_array1_2)

# 1.3 Convert 'np_array1_2' into a Pandas DataFrame named 'df1_3' with columns 'A', 'B', 'C', 'D'.
df1_3 = pd.DataFrame(np_array1_2, columns=['A', 'B', 'C', 'D'])

print("\nDataFrame:")
print(df1_3)

--- Intermediate Pandas Exercise ---
Complete each task by writing the requested Pandas code.
------------------------------------

--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---
Series:
0    10
1    20
2    30
3    40
4    50
dtype: int64

NumPy Array:
[[88 66  6 22]
 [14 66  3 16]
 [99 67 86 80]]

DataFrame:
    A   B   C   D
0  88  66   6  22
1  14  66   3  16
2  99  67  86  80


In [ ]:
# Task 2: Synthetic Data Generation for Practice

In [2]:
import pandas as pd
import numpy as np

# Create DataFrame
df_sales = pd.DataFrame({
    'Date': pd.date_range(start='2023-01-01', end='2023-04-09'),
    'Region': np.random.choice(['East', 'West', 'North', 'South'], 99),
    'Product': np.random.choice(['Laptop', 'Mouse', 'Keyboard', 'Monitor'], 99),
    'Sales': np.random.randint(100, 1001, 99),
    'Quantity': np.random.randint(1, 11, 99)
})

# Introduce 5 NaN values in Sales
sales_nan_index = np.random.choice(df_sales.index, 5, replace=False)
df_sales.loc[sales_nan_index, 'Sales'] = np.nan

# Introduce 3 NaN values in Quantity
quantity_nan_index = np.random.choice(df_sales.index, 3, replace=False)
df_sales.loc[quantity_nan_index, 'Quantity'] = np.nan

# Display first 10 rows
print(df_sales.head(10))

        Date Region   Product  Sales  Quantity
0 2023-01-01  South   Monitor  517.0      10.0
1 2023-01-02  North  Keyboard  597.0      10.0
2 2023-01-03  North   Monitor  177.0       3.0
3 2023-01-04  South   Monitor  909.0       8.0
4 2023-01-05  North   Monitor  703.0       7.0
5 2023-01-06   East   Monitor  646.0       6.0
6 2023-01-07   East     Mouse  416.0       1.0
7 2023-01-08  North     Mouse  946.0       9.0
8 2023-01-09  North     Mouse  980.0       8.0
9 2023-01-10  North     Mouse  327.0       2.0


In [3]:
# --------------------------------------------------
# Task 3: Indexing and Slicing in DataFrames
# --------------------------------------------------

print("\n--- Task 3: Indexing and Slicing in DataFrames ---")

# Use 'df_sales' from Task 2.


# --------------------------------------------------
# 3.1 Select only the 'Region' and 'Sales' columns
# --------------------------------------------------

# Double square brackets [[]] are used to select multiple columns
df3_1 = df_sales[['Region', 'Sales']]

print("\n3.1 Region and Sales columns:")
print(df3_1.head())


# --------------------------------------------------
# 3.2 Select rows where Product is 'Laptop'
# --------------------------------------------------

# Select rows where the Product column value is 'Laptop'
df3_2 = df_sales[df_sales['Product'] == 'Laptop']

print("\n3.2 Rows where Product is Laptop:")
print(df3_2.head())


# --------------------------------------------------
# 3.3 Select rows where Region is 'East'
# AND Sales are greater than 500
# --------------------------------------------------

# '&' represents AND operation
# Each condition must be enclosed in parentheses

df3_3 = df_sales[
    (df_sales['Region'] == 'East') &
    (df_sales['Sales'] > 500)
]

print("\n3.3 Region = East and Sales > 500:")
print(df3_3)


# --------------------------------------------------
# 3.4 Select the Sales value for the first Monitor
# using .loc and .iloc
# --------------------------------------------------

# .loc selects rows and columns by label
# .iloc[0] selects the first matching row

val3_4 = df_sales.loc[
    df_sales['Product'] == 'Monitor',
    'Sales'
].iloc[0]

print("\n3.4 First Monitor Sales value:")
print(val3_4)


--- Task 3: Indexing and Slicing in DataFrames ---

3.1 Region and Sales columns:
  Region  Sales
0  South  517.0
1  North  597.0
2  North  177.0
3  South  909.0
4  North  703.0

3.2 Rows where Product is Laptop:
         Date Region Product  Sales  Quantity
11 2023-01-12  South  Laptop  683.0       7.0
14 2023-01-15   West  Laptop  745.0       8.0
19 2023-01-20   West  Laptop  795.0       6.0
20 2023-01-21  North  Laptop  802.0       3.0
21 2023-01-22  South  Laptop  511.0       6.0

3.3 Region = East and Sales > 500:
         Date Region   Product  Sales  Quantity
5  2023-01-06   East   Monitor  646.0       6.0
24 2023-01-25   East    Laptop  608.0       9.0
25 2023-01-26   East  Keyboard  844.0       4.0
35 2023-02-05   East   Monitor  827.0       5.0
36 2023-02-06   East  Keyboard  501.0       NaN
38 2023-02-08   East  Keyboard  747.0       2.0
70 2023-03-12   East  Keyboard  926.0       9.0
85 2023-03-27   East     Mouse  840.0       9.0
97 2023-04-08   East  Keyboard  746.0     

In [4]:
# Task 4: Data Cleaning (Handling Missing Values)

print("\n--- Task 4: Data Cleaning (Handling Missing Values) ---")

# 4.1 Count missing values in each column
missing_counts4_1 = df_sales.isnull().sum()

print("\nMissing values in each column:")
print(missing_counts4_1)


# 4.2 Fill missing Sales values with the mean
df4_2_filled = df_sales.copy()

sales_mean = df4_2_filled['Sales'].mean()

df4_2_filled['Sales'] = df4_2_filled['Sales'].fillna(sales_mean)

print("\nDataFrame after filling missing Sales values:")
print(df4_2_filled.head())


# 4.3 Drop rows with any missing values
df4_3_dropped = df_sales.dropna()

print("\nDataFrame after dropping rows with missing values:")
print(df4_3_dropped.head())


--- Task 4: Data Cleaning (Handling Missing Values) ---

Missing values in each column:
Date        0
Region      0
Product     0
Sales       5
Quantity    3
dtype: int64

DataFrame after filling missing Sales values:
        Date Region   Product  Sales  Quantity
0 2023-01-01  South   Monitor  517.0      10.0
1 2023-01-02  North  Keyboard  597.0      10.0
2 2023-01-03  North   Monitor  177.0       3.0
3 2023-01-04  South   Monitor  909.0       8.0
4 2023-01-05  North   Monitor  703.0       7.0

DataFrame after dropping rows with missing values:
        Date Region   Product  Sales  Quantity
0 2023-01-01  South   Monitor  517.0      10.0
1 2023-01-02  North  Keyboard  597.0      10.0
2 2023-01-03  North   Monitor  177.0       3.0
3 2023-01-04  South   Monitor  909.0       8.0
4 2023-01-05  North   Monitor  703.0       7.0


In [5]:
# --------------------------------------------------
# Task 5: Data Manipulation (Columns, Sorting, Grouping)
# --------------------------------------------------

print("\n--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---")

# Use the original df_sales DataFrame

# --------------------------------------------------
# 5.1 Create a new column 'Total_Revenue'
# Total_Revenue = Sales * Quantity
# --------------------------------------------------

df_sales['Total_Revenue'] = df_sales['Sales'] * df_sales['Quantity']

print("\n5.1 DataFrame with Total_Revenue column:")
print(df_sales.head())


# --------------------------------------------------
# 5.2 Sort the DataFrame
# First sort by Date in ascending order
# Then sort by Sales in descending order
# --------------------------------------------------

df5_2_sorted = df_sales.sort_values(
    by=['Date', 'Sales'],
    ascending=[True, False]
)

print("\n5.2 Sorted DataFrame:")
print(df5_2_sorted.head())


# --------------------------------------------------
# 5.3 Group by Region
# Calculate the total Sales and Quantity
# --------------------------------------------------

df5_3_grouped_region = df_sales.groupby('Region')[['Sales', 'Quantity']].sum()

print("\n5.3 Total Sales and Quantity by Region:")
print(df5_3_grouped_region)


# --------------------------------------------------
# 5.4 Group by Product
# Calculate the average Sales of each Product
# --------------------------------------------------

df5_4_grouped_product = df_sales.groupby('Product')['Sales'].mean()

print("\n5.4 Average Sales by Product:")
print(df5_4_grouped_product)


--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---

5.1 DataFrame with Total_Revenue column:
        Date Region   Product  Sales  Quantity  Total_Revenue
0 2023-01-01  South   Monitor  517.0      10.0         5170.0
1 2023-01-02  North  Keyboard  597.0      10.0         5970.0
2 2023-01-03  North   Monitor  177.0       3.0          531.0
3 2023-01-04  South   Monitor  909.0       8.0         7272.0
4 2023-01-05  North   Monitor  703.0       7.0         4921.0

5.2 Sorted DataFrame:
        Date Region   Product  Sales  Quantity  Total_Revenue
0 2023-01-01  South   Monitor  517.0      10.0         5170.0
1 2023-01-02  North  Keyboard  597.0      10.0         5970.0
2 2023-01-03  North   Monitor  177.0       3.0          531.0
3 2023-01-04  South   Monitor  909.0       8.0         7272.0
4 2023-01-05  North   Monitor  703.0       7.0         4921.0

5.3 Total Sales and Quantity by Region:
          Sales  Quantity
Region                   
East     9703.0     129.0
North   